repos:
  - repo: local
    hooks:
      - id: prettier
        name: Run Prettier
        language: node
        entry: yarn prettier --write --list-different --ignore-unknown
        types: [text]
      - id: lint
        name: Run ESLint
        language: node
        entry: yarn lint:fix
        pass_filenames: false
      - id: sort-package-json
        name: Sort package.json
        language: node
        entry: yarn sort-package-json
        files: .*package.json
